name: signup_adventure
description: A fun multi-step flutter signup adventure app with animations, avatars, badges, and confetti.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Animation & UI effects
  animated_text_kit: ^4.2.2
  confetti: ^0.7.0

  # Date formatting
  intl: ^0.19.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
